const $=id=>document.getElementById(id),canvas=$("exportCanvas"),ctx=canvas.getContext("2d");
function update(){cardHeadline.textContent=headline.value.trim();cardLeftLabel.textContent=leftLabel.value.trim();cardRightLabel.textContent=rightLabel.value.trim();leftSourceChip.textContent=leftSourceLabel.value.trim()||"Left source";leftSourceChip.href=leftSourceUrl.value.trim()||"#";rightSourceChip.textContent=rightSourceLabel.value.trim()||"Right source";rightSourceChip.href=rightSourceUrl.value.trim()||"#"}
function load(input,side){const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const img=$(side+"PreviewImage");img.src=r.result;img.classList.remove("hidden");$(side+"Placeholder").classList.add("hidden");fit(side)};r.readAsDataURL(f)}
function remove(side){const img=$(side+"PreviewImage");img.removeAttribute("src");img.classList.add("hidden");$(side+"Placeholder").classList.remove("hidden")}
function fit(side){$(side+"PreviewImage").style.objectFit=$(side+"Fit").value}
function wrap(t,m,f){ctx.font=f;const w=String(t||"").trim().split(/\s+/).filter(Boolean),o=[];let l="";w.forEach(x=>{const q=l?l+" "+x:x;if(ctx.measureText(q).width>m&&l){o.push(l);l=x}else l=q});if(l)o.push(l);return o}
function text(t,x,y,m,lh,f,c,n=99,a="left"){ctx.font=f;ctx.fillStyle=c;ctx.textAlign=a;wrap(t,m,f).slice(0,n).forEach((r,i)=>ctx.fillText(r,x,y+i*lh));ctx.textAlign="left"}
function rr(x,y,w,h,r,fill,stroke,lw=1){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function image(img,x,y,w,h,mode){if(!img.complete||!img.naturalWidth)return;const ir=img.naturalWidth/img.naturalHeight,br=w/h;let dw,dh;if((mode==="cover"&&ir>br)||(mode==="contain"&&ir<br)){dh=h;dw=h*ir}else{dw=w;dh=w/ir}ctx.save();ctx.beginPath();ctx.roundRect(x,y,w,h,18);ctx.clip();ctx.fillStyle="#fff";ctx.fillRect(x,y,w,h);ctx.drawImage(img,x+(w-dw)/2,y+(h-dh)/2,dw,dh);ctx.restore()}
function render(){const W=1080,H=1350,m=54,inner=W-m*2,g=86,col=(inner-g)/2,lx=m,rx=m+col+g,top=350,fh=780;ctx.clearRect(0,0,W,H);const bg=ctx.createLinearGradient(0,0,W,0);bg.addColorStop(0,"#dfeaff");bg.addColorStop(.48,"#faf6ef");bg.addColorStop(1,"#ffe2e2");ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);ctx.fillStyle="#185fe6";ctx.beginPath();ctx.arc(W/2-18,60,24,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ef3038";ctx.beginPath();ctx.arc(W/2+18,60,24,0,Math.PI*2);ctx.fill();ctx.textAlign="center";ctx.font="900 42px Arial";ctx.fillStyle="#0d1730";ctx.fillText("DualLens",W/2,78);ctx.font="900 14px Arial";ctx.fillStyle="#667085";ctx.fillText("SAME STORY. DIFFERENT LENS.",W/2,108);text(headline.value.trim().toUpperCase(),W/2,170,inner-40,72,"900 66px Arial","#0d1730",3,"center");ctx.font="900 23px Arial";ctx.fillStyle="#185fe6";ctx.fillText(leftLabel.value.trim().toUpperCase(),lx+col/2,top-26);ctx.fillStyle="#ef3038";ctx.fillText(rightLabel.value.trim().toUpperCase(),rx+col/2,top-26);ctx.textAlign="left";rr(lx,top,col,fh,22,"#fff","rgba(24,95,230,.4)",3);rr(rx,top,col,fh,22,"#fff","rgba(239,48,56,.4)",3);const p=14,ch=50,ih=fh-ch-p*3,li=leftPreviewImage,ri=rightPreviewImage;if(li.src)image(li,lx+p,top+p,col-p*2,ih,leftFit.value);if(ri.src)image(ri,rx+p,top+p,col-p*2,ih,rightFit.value);rr(lx+p,top+fh-ch-p,col-p*2,ch,24,"#fff","rgba(24,95,230,.45)",2);rr(rx+p,top+fh-ch-p,col-p*2,ch,24,"#fff","rgba(239,48,56,.45)",2);ctx.textAlign="center";ctx.font="900 18px Arial";ctx.fillStyle="#185fe6";ctx.fillText(leftSourceLabel.value.trim(),lx+col/2,top+fh-30);ctx.fillStyle="#ef3038";ctx.fillText(rightSourceLabel.value.trim(),rx+col/2,top+fh-30);ctx.strokeStyle="#b6beca";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(W/2,top+20);ctx.lineTo(W/2,top+fh-20);ctx.stroke();rr(W/2-34,top+fh/2-34,68,68,34,"#fff","#b6beca",2);ctx.font="900 24px Arial";ctx.fillStyle="#0d1730";ctx.fillText("VS",W/2,top+fh/2+8);ctx.font="900 28px Arial";ctx.fillText("DualLens",W/2,1285);ctx.textAlign="left"}
["headline","leftLabel","rightLabel","leftSourceLabel","rightSourceLabel","leftSourceUrl","rightSourceUrl"].forEach(id=>$(id).addEventListener("input",update));
leftFit.addEventListener("change",()=>fit("left"));rightFit.addEventListener("change",()=>fit("right"));leftImageInput.addEventListener("change",e=>load(e.target,"left"));rightImageInput.addEventListener("change",e=>load(e.target,"right"));removeLeftBtn.addEventListener("click",()=>remove("left"));removeRightBtn.addEventListener("click",()=>remove("right"));
copyBtn.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(postCopy.value)}catch{postCopy.select();document.execCommand("copy")}message.textContent="Post text copied."});
phonePreviewBtn.addEventListener("click",()=>{render();phoneCopy.textContent=postCopy.value;phoneImage.src=canvas.toDataURL("image/png");phoneDialog.showModal()});closePhoneBtn.addEventListener("click",()=>phoneDialog.close());
exportBtn.addEventListener("click",()=>{render();canvas.toBlob(b=>{if(!b)return;const u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="duallens-comparison.png";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)},"image/png")});update();
